/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface IConnexusCardInterface extends utils.Interface {
  functions: {
    "getNextTokenId()": FunctionFragment;
    "safeMint(address)": FunctionFragment;
    "setERC6551Implementation(address)": FunctionFragment;
    "setERC6551Registry(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getNextTokenId"
      | "safeMint"
      | "setERC6551Implementation"
      | "setERC6551Registry"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getNextTokenId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "safeMint", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setERC6551Implementation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setERC6551Registry",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getNextTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "safeMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setERC6551Implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setERC6551Registry",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IConnexusCard extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IConnexusCardInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getNextTokenId(overrides?: CallOverrides): Promise<[BigNumber]>;

    safeMint(
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setERC6551Implementation(
      implementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setERC6551Registry(
      registry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  getNextTokenId(overrides?: CallOverrides): Promise<BigNumber>;

  safeMint(
    to: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setERC6551Implementation(
    implementation: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setERC6551Registry(
    registry: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    getNextTokenId(overrides?: CallOverrides): Promise<BigNumber>;

    safeMint(to: string, overrides?: CallOverrides): Promise<BigNumber>;

    setERC6551Implementation(
      implementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setERC6551Registry(
      registry: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getNextTokenId(overrides?: CallOverrides): Promise<BigNumber>;

    safeMint(
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setERC6551Implementation(
      implementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setERC6551Registry(
      registry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getNextTokenId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    safeMint(
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setERC6551Implementation(
      implementation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setERC6551Registry(
      registry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
