/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface IRWACarInterface extends utils.Interface {
  functions: {
    "_mintWithTokens(address)": FunctionFragment;
    "safeMint(uint256,string,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "_mintWithTokens" | "safeMint"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_mintWithTokens",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "safeMint",
    values: [BigNumberish, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "_mintWithTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "safeMint", data: BytesLike): Result;

  events: {};
}

export interface IRWACar extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRWACarInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _mintWithTokens(
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    safeMint(
      numberChassi: BigNumberish,
      doclink: string,
      accountOrTBA: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  _mintWithTokens(
    recipient: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  safeMint(
    numberChassi: BigNumberish,
    doclink: string,
    accountOrTBA: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    _mintWithTokens(
      recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    safeMint(
      numberChassi: BigNumberish,
      doclink: string,
      accountOrTBA: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    _mintWithTokens(
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    safeMint(
      numberChassi: BigNumberish,
      doclink: string,
      accountOrTBA: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _mintWithTokens(
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    safeMint(
      numberChassi: BigNumberish,
      doclink: string,
      accountOrTBA: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
