/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IConnexusCard, IConnexusCardInterface } from "../IConnexusCard";

const _abi = [
  {
    inputs: [],
    name: "getNextTokenId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "safeMint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "setERC6551Implementation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "registry",
        type: "address",
      },
    ],
    name: "setERC6551Registry",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IConnexusCard__factory {
  static readonly abi = _abi;
  static createInterface(): IConnexusCardInterface {
    return new utils.Interface(_abi) as IConnexusCardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConnexusCard {
    return new Contract(address, _abi, signerOrProvider) as IConnexusCard;
  }
}
