/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IRWARealstate, IRWARealstateInterface } from "../IRWARealstate";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "number",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "linkdoc",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "fraction",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "accountOrTBA",
        type: "address",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRWARealstate__factory {
  static readonly abi = _abi;
  static createInterface(): IRWARealstateInterface {
    return new utils.Interface(_abi) as IRWARealstateInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRWARealstate {
    return new Contract(address, _abi, signerOrProvider) as IRWARealstate;
  }
}
