/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace VmSafe {
  export type LogStruct = {
    topics: BytesLike[];
    data: BytesLike;
    emitter: string;
  };

  export type LogStructOutput = [string[], string, string] & {
    topics: string[];
    data: string;
    emitter: string;
  };

  export type RpcStruct = { key: string; url: string };

  export type RpcStructOutput = [string, string] & { key: string; url: string };
}

export interface VmSafeInterface extends utils.Interface {
  functions: {
    "accesses(address)": FunctionFragment;
    "addr(uint256)": FunctionFragment;
    "assume(bool)": FunctionFragment;
    "broadcast()": FunctionFragment;
    "broadcast(address)": FunctionFragment;
    "broadcast(uint256)": FunctionFragment;
    "closeFile(string)": FunctionFragment;
    "deriveKey(string,uint32)": FunctionFragment;
    "deriveKey(string,string,uint32)": FunctionFragment;
    "envAddress(string)": FunctionFragment;
    "envAddress(string,string)": FunctionFragment;
    "envBool(string)": FunctionFragment;
    "envBool(string,string)": FunctionFragment;
    "envBytes(string)": FunctionFragment;
    "envBytes(string,string)": FunctionFragment;
    "envBytes32(string,string)": FunctionFragment;
    "envBytes32(string)": FunctionFragment;
    "envInt(string,string)": FunctionFragment;
    "envInt(string)": FunctionFragment;
    "envString(string,string)": FunctionFragment;
    "envString(string)": FunctionFragment;
    "envUint(string)": FunctionFragment;
    "envUint(string,string)": FunctionFragment;
    "ffi(string[])": FunctionFragment;
    "getCode(string)": FunctionFragment;
    "getDeployedCode(string)": FunctionFragment;
    "getNonce(address)": FunctionFragment;
    "getRecordedLogs()": FunctionFragment;
    "label(address,string)": FunctionFragment;
    "load(address,bytes32)": FunctionFragment;
    "parseAddress(string)": FunctionFragment;
    "parseBool(string)": FunctionFragment;
    "parseBytes(string)": FunctionFragment;
    "parseBytes32(string)": FunctionFragment;
    "parseInt(string)": FunctionFragment;
    "parseJson(string)": FunctionFragment;
    "parseJson(string,string)": FunctionFragment;
    "parseUint(string)": FunctionFragment;
    "projectRoot()": FunctionFragment;
    "readFile(string)": FunctionFragment;
    "readFileBinary(string)": FunctionFragment;
    "readLine(string)": FunctionFragment;
    "record()": FunctionFragment;
    "recordLogs()": FunctionFragment;
    "rememberKey(uint256)": FunctionFragment;
    "removeFile(string)": FunctionFragment;
    "rpcUrl(string)": FunctionFragment;
    "rpcUrlStructs()": FunctionFragment;
    "rpcUrls()": FunctionFragment;
    "serializeAddress(string,string,address[])": FunctionFragment;
    "serializeAddress(string,string,address)": FunctionFragment;
    "serializeBool(string,string,bool[])": FunctionFragment;
    "serializeBool(string,string,bool)": FunctionFragment;
    "serializeBytes(string,string,bytes[])": FunctionFragment;
    "serializeBytes(string,string,bytes)": FunctionFragment;
    "serializeBytes32(string,string,bytes32[])": FunctionFragment;
    "serializeBytes32(string,string,bytes32)": FunctionFragment;
    "serializeInt(string,string,int256)": FunctionFragment;
    "serializeInt(string,string,int256[])": FunctionFragment;
    "serializeString(string,string,string[])": FunctionFragment;
    "serializeString(string,string,string)": FunctionFragment;
    "serializeUint(string,string,uint256)": FunctionFragment;
    "serializeUint(string,string,uint256[])": FunctionFragment;
    "setEnv(string,string)": FunctionFragment;
    "sign(uint256,bytes32)": FunctionFragment;
    "startBroadcast()": FunctionFragment;
    "startBroadcast(address)": FunctionFragment;
    "startBroadcast(uint256)": FunctionFragment;
    "stopBroadcast()": FunctionFragment;
    "toString(address)": FunctionFragment;
    "toString(uint256)": FunctionFragment;
    "toString(bytes)": FunctionFragment;
    "toString(bool)": FunctionFragment;
    "toString(int256)": FunctionFragment;
    "toString(bytes32)": FunctionFragment;
    "writeFile(string,string)": FunctionFragment;
    "writeFileBinary(string,bytes)": FunctionFragment;
    "writeJson(string,string,string)": FunctionFragment;
    "writeJson(string,string)": FunctionFragment;
    "writeLine(string,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "accesses"
      | "addr"
      | "assume"
      | "broadcast()"
      | "broadcast(address)"
      | "broadcast(uint256)"
      | "closeFile"
      | "deriveKey(string,uint32)"
      | "deriveKey(string,string,uint32)"
      | "envAddress(string)"
      | "envAddress(string,string)"
      | "envBool(string)"
      | "envBool(string,string)"
      | "envBytes(string)"
      | "envBytes(string,string)"
      | "envBytes32(string,string)"
      | "envBytes32(string)"
      | "envInt(string,string)"
      | "envInt(string)"
      | "envString(string,string)"
      | "envString(string)"
      | "envUint(string)"
      | "envUint(string,string)"
      | "ffi"
      | "getCode"
      | "getDeployedCode"
      | "getNonce"
      | "getRecordedLogs"
      | "label"
      | "load"
      | "parseAddress"
      | "parseBool"
      | "parseBytes"
      | "parseBytes32"
      | "parseInt"
      | "parseJson(string)"
      | "parseJson(string,string)"
      | "parseUint"
      | "projectRoot"
      | "readFile"
      | "readFileBinary"
      | "readLine"
      | "record"
      | "recordLogs"
      | "rememberKey"
      | "removeFile"
      | "rpcUrl"
      | "rpcUrlStructs"
      | "rpcUrls"
      | "serializeAddress(string,string,address[])"
      | "serializeAddress(string,string,address)"
      | "serializeBool(string,string,bool[])"
      | "serializeBool(string,string,bool)"
      | "serializeBytes(string,string,bytes[])"
      | "serializeBytes(string,string,bytes)"
      | "serializeBytes32(string,string,bytes32[])"
      | "serializeBytes32(string,string,bytes32)"
      | "serializeInt(string,string,int256)"
      | "serializeInt(string,string,int256[])"
      | "serializeString(string,string,string[])"
      | "serializeString(string,string,string)"
      | "serializeUint(string,string,uint256)"
      | "serializeUint(string,string,uint256[])"
      | "setEnv"
      | "sign"
      | "startBroadcast()"
      | "startBroadcast(address)"
      | "startBroadcast(uint256)"
      | "stopBroadcast"
      | "toString(address)"
      | "toString(uint256)"
      | "toString(bytes)"
      | "toString(bool)"
      | "toString(int256)"
      | "toString(bytes32)"
      | "writeFile"
      | "writeFileBinary"
      | "writeJson(string,string,string)"
      | "writeJson(string,string)"
      | "writeLine"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "accesses", values: [string]): string;
  encodeFunctionData(functionFragment: "addr", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "assume", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "broadcast()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "broadcast(address)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "broadcast(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "closeFile", values: [string]): string;
  encodeFunctionData(
    functionFragment: "deriveKey(string,uint32)",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deriveKey(string,string,uint32)",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "envAddress(string)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "envAddress(string,string)",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "envBool(string)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "envBool(string,string)",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "envBytes(string)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "envBytes(string,string)",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "envBytes32(string,string)",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "envBytes32(string)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "envInt(string,string)",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "envInt(string)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "envString(string,string)",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "envString(string)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "envUint(string)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "envUint(string,string)",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "ffi", values: [string[]]): string;
  encodeFunctionData(functionFragment: "getCode", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getDeployedCode",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getNonce", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getRecordedLogs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "label",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "load",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "parseAddress",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "parseBool", values: [string]): string;
  encodeFunctionData(functionFragment: "parseBytes", values: [string]): string;
  encodeFunctionData(
    functionFragment: "parseBytes32",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "parseInt", values: [string]): string;
  encodeFunctionData(
    functionFragment: "parseJson(string)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "parseJson(string,string)",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "parseUint", values: [string]): string;
  encodeFunctionData(
    functionFragment: "projectRoot",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "readFile", values: [string]): string;
  encodeFunctionData(
    functionFragment: "readFileBinary",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "readLine", values: [string]): string;
  encodeFunctionData(functionFragment: "record", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordLogs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rememberKey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "removeFile", values: [string]): string;
  encodeFunctionData(functionFragment: "rpcUrl", values: [string]): string;
  encodeFunctionData(
    functionFragment: "rpcUrlStructs",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "rpcUrls", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "serializeAddress(string,string,address[])",
    values: [string, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeAddress(string,string,address)",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeBool(string,string,bool[])",
    values: [string, string, boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeBool(string,string,bool)",
    values: [string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeBytes(string,string,bytes[])",
    values: [string, string, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeBytes(string,string,bytes)",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeBytes32(string,string,bytes32[])",
    values: [string, string, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeBytes32(string,string,bytes32)",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeInt(string,string,int256)",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeInt(string,string,int256[])",
    values: [string, string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeString(string,string,string[])",
    values: [string, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeString(string,string,string)",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeUint(string,string,uint256)",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeUint(string,string,uint256[])",
    values: [string, string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setEnv",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sign",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startBroadcast()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startBroadcast(address)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "startBroadcast(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stopBroadcast",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toString(address)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "toString(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toString(bytes)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "toString(bool)",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "toString(int256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toString(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "writeFile",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "writeFileBinary",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "writeJson(string,string,string)",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "writeJson(string,string)",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "writeLine",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "accesses", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assume", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "broadcast()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "broadcast(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "broadcast(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "closeFile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deriveKey(string,uint32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deriveKey(string,string,uint32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "envAddress(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "envAddress(string,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "envBool(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "envBool(string,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "envBytes(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "envBytes(string,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "envBytes32(string,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "envBytes32(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "envInt(string,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "envInt(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "envString(string,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "envString(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "envUint(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "envUint(string,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ffi", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDeployedCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecordedLogs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "label", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "load", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "parseAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "parseBool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "parseBytes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "parseBytes32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "parseInt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "parseJson(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "parseJson(string,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "parseUint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "projectRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "readFile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "readFileBinary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "readLine", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "record", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recordLogs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rememberKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removeFile", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rpcUrl", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rpcUrlStructs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rpcUrls", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "serializeAddress(string,string,address[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeAddress(string,string,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeBool(string,string,bool[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeBool(string,string,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeBytes(string,string,bytes[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeBytes(string,string,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeBytes32(string,string,bytes32[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeBytes32(string,string,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeInt(string,string,int256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeInt(string,string,int256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeString(string,string,string[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeString(string,string,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeUint(string,string,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeUint(string,string,uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setEnv", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sign", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startBroadcast()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startBroadcast(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startBroadcast(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stopBroadcast",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toString(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toString(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toString(bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toString(bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toString(int256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toString(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "writeFile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "writeFileBinary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "writeJson(string,string,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "writeJson(string,string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "writeLine", data: BytesLike): Result;

  events: {};
}

export interface VmSafe extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VmSafeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accesses(
      arg0: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    addr(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    assume(arg0: boolean, overrides?: CallOverrides): Promise<[void]>;

    "broadcast()"(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "broadcast(address)"(
      arg0: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "broadcast(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    closeFile(
      arg0: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "deriveKey(string,uint32)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "deriveKey(string,string,uint32)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "envAddress(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "envAddress(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    "envBool(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "envBool(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean[]]>;

    "envBytes(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "envBytes(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    "envBytes32(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    "envBytes32(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "envInt(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    "envInt(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "envString(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    "envString(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "envUint(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "envUint(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    ffi(
      arg0: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getCode(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    getDeployedCode(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    getNonce(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getRecordedLogs(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    label(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    load(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    parseAddress(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    parseBool(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    parseBytes(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    parseBytes32(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    parseInt(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "parseJson(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "parseJson(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    parseUint(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    projectRoot(overrides?: CallOverrides): Promise<[string]>;

    readFile(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    readFileBinary(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    readLine(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    record(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    recordLogs(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    rememberKey(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    removeFile(
      arg0: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    rpcUrl(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    rpcUrlStructs(
      overrides?: CallOverrides
    ): Promise<[VmSafe.RpcStructOutput[]]>;

    rpcUrls(overrides?: CallOverrides): Promise<[[string, string][]]>;

    "serializeAddress(string,string,address[])"(
      arg0: string,
      arg1: string,
      arg2: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "serializeAddress(string,string,address)"(
      arg0: string,
      arg1: string,
      arg2: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "serializeBool(string,string,bool[])"(
      arg0: string,
      arg1: string,
      arg2: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "serializeBool(string,string,bool)"(
      arg0: string,
      arg1: string,
      arg2: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "serializeBytes(string,string,bytes[])"(
      arg0: string,
      arg1: string,
      arg2: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "serializeBytes(string,string,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "serializeBytes32(string,string,bytes32[])"(
      arg0: string,
      arg1: string,
      arg2: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "serializeBytes32(string,string,bytes32)"(
      arg0: string,
      arg1: string,
      arg2: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "serializeInt(string,string,int256)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "serializeInt(string,string,int256[])"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "serializeString(string,string,string[])"(
      arg0: string,
      arg1: string,
      arg2: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "serializeString(string,string,string)"(
      arg0: string,
      arg1: string,
      arg2: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "serializeUint(string,string,uint256)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "serializeUint(string,string,uint256[])"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setEnv(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    sign(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<[number, string, string]>;

    "startBroadcast()"(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "startBroadcast(address)"(
      arg0: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "startBroadcast(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    stopBroadcast(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "toString(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "toString(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "toString(bytes)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "toString(bool)"(
      arg0: boolean,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "toString(int256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "toString(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    writeFile(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    writeFileBinary(
      arg0: string,
      arg1: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "writeJson(string,string,string)"(
      arg0: string,
      arg1: string,
      arg2: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    "writeJson(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    writeLine(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  accesses(
    arg0: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  addr(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  assume(arg0: boolean, overrides?: CallOverrides): Promise<void>;

  "broadcast()"(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "broadcast(address)"(
    arg0: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "broadcast(uint256)"(
    arg0: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  closeFile(
    arg0: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "deriveKey(string,uint32)"(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "deriveKey(string,string,uint32)"(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "envAddress(string)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "envAddress(string,string)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  "envBool(string)"(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "envBool(string,string)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean[]>;

  "envBytes(string)"(arg0: string, overrides?: CallOverrides): Promise<string>;

  "envBytes(string,string)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  "envBytes32(string,string)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  "envBytes32(string)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "envInt(string,string)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  "envInt(string)"(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "envString(string,string)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  "envString(string)"(arg0: string, overrides?: CallOverrides): Promise<string>;

  "envUint(string)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "envUint(string,string)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  ffi(
    arg0: string[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getCode(arg0: string, overrides?: CallOverrides): Promise<string>;

  getDeployedCode(arg0: string, overrides?: CallOverrides): Promise<string>;

  getNonce(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  getRecordedLogs(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  label(
    arg0: string,
    arg1: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  load(
    arg0: string,
    arg1: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  parseAddress(arg0: string, overrides?: CallOverrides): Promise<string>;

  parseBool(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  parseBytes(arg0: string, overrides?: CallOverrides): Promise<string>;

  parseBytes32(arg0: string, overrides?: CallOverrides): Promise<string>;

  parseInt(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "parseJson(string)"(arg0: string, overrides?: CallOverrides): Promise<string>;

  "parseJson(string,string)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<string>;

  parseUint(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  projectRoot(overrides?: CallOverrides): Promise<string>;

  readFile(arg0: string, overrides?: CallOverrides): Promise<string>;

  readFileBinary(arg0: string, overrides?: CallOverrides): Promise<string>;

  readLine(arg0: string, overrides?: CallOverrides): Promise<string>;

  record(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  recordLogs(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  rememberKey(
    arg0: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  removeFile(
    arg0: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  rpcUrl(arg0: string, overrides?: CallOverrides): Promise<string>;

  rpcUrlStructs(overrides?: CallOverrides): Promise<VmSafe.RpcStructOutput[]>;

  rpcUrls(overrides?: CallOverrides): Promise<[string, string][]>;

  "serializeAddress(string,string,address[])"(
    arg0: string,
    arg1: string,
    arg2: string[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "serializeAddress(string,string,address)"(
    arg0: string,
    arg1: string,
    arg2: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "serializeBool(string,string,bool[])"(
    arg0: string,
    arg1: string,
    arg2: boolean[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "serializeBool(string,string,bool)"(
    arg0: string,
    arg1: string,
    arg2: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "serializeBytes(string,string,bytes[])"(
    arg0: string,
    arg1: string,
    arg2: BytesLike[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "serializeBytes(string,string,bytes)"(
    arg0: string,
    arg1: string,
    arg2: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "serializeBytes32(string,string,bytes32[])"(
    arg0: string,
    arg1: string,
    arg2: BytesLike[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "serializeBytes32(string,string,bytes32)"(
    arg0: string,
    arg1: string,
    arg2: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "serializeInt(string,string,int256)"(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "serializeInt(string,string,int256[])"(
    arg0: string,
    arg1: string,
    arg2: BigNumberish[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "serializeString(string,string,string[])"(
    arg0: string,
    arg1: string,
    arg2: string[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "serializeString(string,string,string)"(
    arg0: string,
    arg1: string,
    arg2: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "serializeUint(string,string,uint256)"(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "serializeUint(string,string,uint256[])"(
    arg0: string,
    arg1: string,
    arg2: BigNumberish[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setEnv(
    arg0: string,
    arg1: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  sign(
    arg0: BigNumberish,
    arg1: BytesLike,
    overrides?: CallOverrides
  ): Promise<[number, string, string]>;

  "startBroadcast()"(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "startBroadcast(address)"(
    arg0: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "startBroadcast(uint256)"(
    arg0: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  stopBroadcast(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "toString(address)"(arg0: string, overrides?: CallOverrides): Promise<string>;

  "toString(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "toString(bytes)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "toString(bool)"(arg0: boolean, overrides?: CallOverrides): Promise<string>;

  "toString(int256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "toString(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  writeFile(
    arg0: string,
    arg1: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  writeFileBinary(
    arg0: string,
    arg1: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "writeJson(string,string,string)"(
    arg0: string,
    arg1: string,
    arg2: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  "writeJson(string,string)"(
    arg0: string,
    arg1: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  writeLine(
    arg0: string,
    arg1: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    accesses(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string[], string[]] & { reads: string[]; writes: string[] }>;

    addr(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    assume(arg0: boolean, overrides?: CallOverrides): Promise<void>;

    "broadcast()"(overrides?: CallOverrides): Promise<void>;

    "broadcast(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "broadcast(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    closeFile(arg0: string, overrides?: CallOverrides): Promise<void>;

    "deriveKey(string,uint32)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "deriveKey(string,string,uint32)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envAddress(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "envAddress(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "envBool(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "envBool(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean[]>;

    "envBytes(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "envBytes(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "envBytes32(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "envBytes32(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "envInt(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    "envInt(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envString(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "envString(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "envUint(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envUint(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    ffi(arg0: string[], overrides?: CallOverrides): Promise<string>;

    getCode(arg0: string, overrides?: CallOverrides): Promise<string>;

    getDeployedCode(arg0: string, overrides?: CallOverrides): Promise<string>;

    getNonce(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getRecordedLogs(
      overrides?: CallOverrides
    ): Promise<VmSafe.LogStructOutput[]>;

    label(arg0: string, arg1: string, overrides?: CallOverrides): Promise<void>;

    load(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    parseAddress(arg0: string, overrides?: CallOverrides): Promise<string>;

    parseBool(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    parseBytes(arg0: string, overrides?: CallOverrides): Promise<string>;

    parseBytes32(arg0: string, overrides?: CallOverrides): Promise<string>;

    parseInt(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "parseJson(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "parseJson(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<string>;

    parseUint(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    projectRoot(overrides?: CallOverrides): Promise<string>;

    readFile(arg0: string, overrides?: CallOverrides): Promise<string>;

    readFileBinary(arg0: string, overrides?: CallOverrides): Promise<string>;

    readLine(arg0: string, overrides?: CallOverrides): Promise<string>;

    record(overrides?: CallOverrides): Promise<void>;

    recordLogs(overrides?: CallOverrides): Promise<void>;

    rememberKey(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    removeFile(arg0: string, overrides?: CallOverrides): Promise<void>;

    rpcUrl(arg0: string, overrides?: CallOverrides): Promise<string>;

    rpcUrlStructs(overrides?: CallOverrides): Promise<VmSafe.RpcStructOutput[]>;

    rpcUrls(overrides?: CallOverrides): Promise<[string, string][]>;

    "serializeAddress(string,string,address[])"(
      arg0: string,
      arg1: string,
      arg2: string[],
      overrides?: CallOverrides
    ): Promise<string>;

    "serializeAddress(string,string,address)"(
      arg0: string,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "serializeBool(string,string,bool[])"(
      arg0: string,
      arg1: string,
      arg2: boolean[],
      overrides?: CallOverrides
    ): Promise<string>;

    "serializeBool(string,string,bool)"(
      arg0: string,
      arg1: string,
      arg2: boolean,
      overrides?: CallOverrides
    ): Promise<string>;

    "serializeBytes(string,string,bytes[])"(
      arg0: string,
      arg1: string,
      arg2: BytesLike[],
      overrides?: CallOverrides
    ): Promise<string>;

    "serializeBytes(string,string,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "serializeBytes32(string,string,bytes32[])"(
      arg0: string,
      arg1: string,
      arg2: BytesLike[],
      overrides?: CallOverrides
    ): Promise<string>;

    "serializeBytes32(string,string,bytes32)"(
      arg0: string,
      arg1: string,
      arg2: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "serializeInt(string,string,int256)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "serializeInt(string,string,int256[])"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<string>;

    "serializeString(string,string,string[])"(
      arg0: string,
      arg1: string,
      arg2: string[],
      overrides?: CallOverrides
    ): Promise<string>;

    "serializeString(string,string,string)"(
      arg0: string,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "serializeUint(string,string,uint256)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "serializeUint(string,string,uint256[])"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<string>;

    setEnv(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    sign(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<[number, string, string]>;

    "startBroadcast()"(overrides?: CallOverrides): Promise<void>;

    "startBroadcast(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "startBroadcast(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    stopBroadcast(overrides?: CallOverrides): Promise<void>;

    "toString(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "toString(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "toString(bytes)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "toString(bool)"(arg0: boolean, overrides?: CallOverrides): Promise<string>;

    "toString(int256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "toString(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    writeFile(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    writeFileBinary(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "writeJson(string,string,string)"(
      arg0: string,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "writeJson(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    writeLine(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    accesses(
      arg0: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    addr(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    assume(arg0: boolean, overrides?: CallOverrides): Promise<BigNumber>;

    "broadcast()"(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "broadcast(address)"(
      arg0: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "broadcast(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    closeFile(
      arg0: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "deriveKey(string,uint32)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "deriveKey(string,string,uint32)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envAddress(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envAddress(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envBool(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envBool(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envBytes(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envBytes(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envBytes32(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envBytes32(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envInt(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envInt(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envString(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envString(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envUint(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "envUint(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ffi(
      arg0: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getCode(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getDeployedCode(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNonce(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getRecordedLogs(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    label(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    load(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    parseAddress(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    parseBool(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    parseBytes(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    parseBytes32(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    parseInt(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "parseJson(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "parseJson(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    parseUint(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    projectRoot(overrides?: CallOverrides): Promise<BigNumber>;

    readFile(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    readFileBinary(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    readLine(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    record(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    recordLogs(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    rememberKey(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    removeFile(
      arg0: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    rpcUrl(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    rpcUrlStructs(overrides?: CallOverrides): Promise<BigNumber>;

    rpcUrls(overrides?: CallOverrides): Promise<BigNumber>;

    "serializeAddress(string,string,address[])"(
      arg0: string,
      arg1: string,
      arg2: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "serializeAddress(string,string,address)"(
      arg0: string,
      arg1: string,
      arg2: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "serializeBool(string,string,bool[])"(
      arg0: string,
      arg1: string,
      arg2: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "serializeBool(string,string,bool)"(
      arg0: string,
      arg1: string,
      arg2: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "serializeBytes(string,string,bytes[])"(
      arg0: string,
      arg1: string,
      arg2: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "serializeBytes(string,string,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "serializeBytes32(string,string,bytes32[])"(
      arg0: string,
      arg1: string,
      arg2: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "serializeBytes32(string,string,bytes32)"(
      arg0: string,
      arg1: string,
      arg2: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "serializeInt(string,string,int256)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "serializeInt(string,string,int256[])"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "serializeString(string,string,string[])"(
      arg0: string,
      arg1: string,
      arg2: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "serializeString(string,string,string)"(
      arg0: string,
      arg1: string,
      arg2: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "serializeUint(string,string,uint256)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "serializeUint(string,string,uint256[])"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setEnv(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    sign(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "startBroadcast()"(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "startBroadcast(address)"(
      arg0: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "startBroadcast(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    stopBroadcast(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "toString(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "toString(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "toString(bytes)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "toString(bool)"(
      arg0: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "toString(int256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "toString(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    writeFile(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    writeFileBinary(
      arg0: string,
      arg1: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "writeJson(string,string,string)"(
      arg0: string,
      arg1: string,
      arg2: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    "writeJson(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    writeLine(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accesses(
      arg0: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    addr(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    assume(
      arg0: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "broadcast()"(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "broadcast(address)"(
      arg0: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "broadcast(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    closeFile(
      arg0: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "deriveKey(string,uint32)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "deriveKey(string,string,uint32)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "envAddress(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "envAddress(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "envBool(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "envBool(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "envBytes(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "envBytes(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "envBytes32(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "envBytes32(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "envInt(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "envInt(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "envString(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "envString(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "envUint(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "envUint(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ffi(
      arg0: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getCode(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDeployedCode(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNonce(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRecordedLogs(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    label(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    load(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parseAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parseBool(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parseBytes(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parseBytes32(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parseInt(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "parseJson(string)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "parseJson(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parseUint(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projectRoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    readFile(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    readFileBinary(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    readLine(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    record(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    recordLogs(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    rememberKey(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    removeFile(
      arg0: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    rpcUrl(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rpcUrlStructs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rpcUrls(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "serializeAddress(string,string,address[])"(
      arg0: string,
      arg1: string,
      arg2: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "serializeAddress(string,string,address)"(
      arg0: string,
      arg1: string,
      arg2: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "serializeBool(string,string,bool[])"(
      arg0: string,
      arg1: string,
      arg2: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "serializeBool(string,string,bool)"(
      arg0: string,
      arg1: string,
      arg2: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "serializeBytes(string,string,bytes[])"(
      arg0: string,
      arg1: string,
      arg2: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "serializeBytes(string,string,bytes)"(
      arg0: string,
      arg1: string,
      arg2: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "serializeBytes32(string,string,bytes32[])"(
      arg0: string,
      arg1: string,
      arg2: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "serializeBytes32(string,string,bytes32)"(
      arg0: string,
      arg1: string,
      arg2: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "serializeInt(string,string,int256)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "serializeInt(string,string,int256[])"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "serializeString(string,string,string[])"(
      arg0: string,
      arg1: string,
      arg2: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "serializeString(string,string,string)"(
      arg0: string,
      arg1: string,
      arg2: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "serializeUint(string,string,uint256)"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "serializeUint(string,string,uint256[])"(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setEnv(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    sign(
      arg0: BigNumberish,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "startBroadcast()"(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "startBroadcast(address)"(
      arg0: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "startBroadcast(uint256)"(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    stopBroadcast(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "toString(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "toString(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "toString(bytes)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "toString(bool)"(
      arg0: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "toString(int256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "toString(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    writeFile(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    writeFileBinary(
      arg0: string,
      arg1: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "writeJson(string,string,string)"(
      arg0: string,
      arg1: string,
      arg2: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    "writeJson(string,string)"(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    writeLine(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
